require("abhishek.plugins-setup")
require("abhishek.core.options")
require("abhishek.core.keymaps")
require("abhishek.core.colorscheme")
require("abhishek.plugins.comment")
require("abhishek.plugins.nvim-tree")
require("abhishek.plugins.lualine")
